### ISSUE TITLE
CAMS Desktop: Handle requirement to create contact for CallCentre submissions in the same way as Public fault report submissions

### ISSUE THREAD

**Issue by richardcesdm** [exeGesIS-SDM/CAMS-Desktop#42]
For public fault reports, if made by a call centre user there is a need to create a new contact each time. If the desktop user tries to accept them without first creating a new contact the following dialogue box appears:

![image](https://user-images.githubusercontent.com/24268198/52863465-d9465580-312f-11e9-88d3-bd0518d697be.png)

At the moment if the user tries to do the same thing for Request Update submissions made by a call centre user the following less friendly message appears: 

![image](https://user-images.githubusercontent.com/24268198/52863416-b6b43c80-312f-11e9-8ede-9c4a64080ea0.png)

It would be nice if the same message could appear. I'm not sure what logic currently checks in the case of issue submissions but doesn't catch request update submissions. 

This will probably need someone to coordinate with me to make sure there is valid data to replicate this with so just give me a shout when we have some time to look at this. As it only effects 1 type of submission that is not widely used I'm classing as low priority.

**Comment by Timothy-D** [comment]
@richardcesdm please can you make sure there are some suitable submissions the the CAMS_Dev_Master database?

**Comment by richardcesdm** [comment]
@Timothy-D within the CAMS_Dev_master database on dev-sql-1 the webholding records with webholdingID of 
1796
1795
Can be used to reproduce this problem. At present when the Maint1/Adduser record is processed the user doing the processing will get the error described in the problem above and they will also receive a follow up message advising that the record has failed to process, however this turns out not to be true as the record is still processed through. After the record is processed through the call centre contact is linked but (unsurprisingly) there is no contact linked to reflect the member of public (as none was created)

**Comment by Timothy-D** [comment]
The check for type & contact on public faults happens when the record is accepted, I have put in a check for contacts on add user submissions in the same place. It is possible that the user could ignore this and process anyway, I think this applies to both.
This will need testing.

The confusion over whether the sproc has failed or not is mainly due to the procedure itself not checking for errors after each insert. Line 342 carries out an insert, which is immediately followed by another insert on line 364; the error check comes in at line 389 - if the first insert fails but the second doesn't this won't get picked up, as it only checks the last action for errors

**Comment by richardcesdm** [comment]
I have now tested this in v7.2.3 and can confirm it is a much improved user experience. I have also added some extra error log checks into usp_process_Maint_AddUser to ensure that it will roll back properly when the user fails to create a contact.

**Comment by Timothy-D** [comment]
signing off
